# docker-compose.prod.yml
version: '3.8'

services:
  # Backend FastAPI Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8010:8010"
    volumes:
      # Update the volume path to use the new workdir
      - chroma-data:/backend/chroma_db
    command: uvicorn main:app --host 0.0.0.0 --port 8010
    restart: unless-stopped

  # Frontend Next.js Service
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  chroma-data: