# --- Build Stage ---
FROM node:20-alpine AS builder

# Set the working directory for the build stage
WORKDIR /frontend

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

# Copy package.json and lock files
COPY package*.json ./
RUN npm install

# Copy the rest of the application source code
COPY . .
RUN npm run build

# --- Production Stage ---
FROM node:20-alpine

# Set the working directory for the production stage
WORKDIR /frontend

# --- Add Healthcheck Dependency ---
# Install curl for the healthcheck
RUN apk add --no-cache curl

# Copy only the necessary build artifacts from the builder stage
COPY --from=builder /frontend/.next ./.next
COPY --from=builder /frontend/node_modules ./node_modules
COPY --from=builder /frontend/package.json ./package.json
COPY --from=builder /frontend/public ./public
COPY --from=builder /frontend/next.config.ts ./

EXPOSE 3000

# The command to start the optimized Next.js server
CMD ["npm", "start"]


HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:3000/ || exit 1